export const teams = {
  'paris-levallois': 'Metropolitans 92',
  villeurbanne: 'LDLC ASVEL',
  monaco: 'AS Monaco Basket',
  dijon: 'JDA Dijon',
  'le-mans': 'Le Mans Sarthe Basket',
  'pau-orthez': 'Élan Béarnais Pau-Lacq-Orthez',
  strasbourg: 'SIG Strasbourg',
  limoges: 'Limoges CSP',
  nanterre: 'Nanterre 92',
  gravelines: 'BCM Gravelines-Dunkerque',
  bourg: 'JL Bourg',
  roanne: 'Chorale Roanne Basket',
  cholet: 'Cholet Basket',
  orleans: 'Orléans Loiret Basket',
  'le-portel': 'ESSM Le Portel',
  'paris-basket': 'Paris Basketball',
  'chalons-en-champagne': 'Champagne Basket',
  'fos-provence': 'Fos Provence',
}
