export const teams = {
  'paris-levallois': 'Metropolitans 92',
  villeurbanne: 'LDLC ASVEL',
  monaco: 'AS Monaco Basket',
  dijon: 'JDA Dijon',
  'le-mans': 'Le Mans Sarthe Basket',
  'pau-orthez': 'Élan Béarnais Pau-Lacq-Orthez',
  strasbourg: 'SIG Strasbourg',
  limoges: 'Limoges CSP',
  nanterre: 'Nanterre 92',
  gravelines: 'BCM Gravelines-Dunkerque',
  bourg: 'JL Bourg',
  roanne: 'Chorale Roanne Basket',
  cholet: 'Cholet Basket',
  orleans: 'Orléans Loiret Basket',
  'le-portel': 'ESSM Le Portel',
  'paris-basket': 'Paris Basketball',
  'chalons-en-champagne': 'Champagne Basket',
  'fos-provence': 'Fos Provence',
}

export const computeTeams = {
  Metropolitans: 'Metropolitans 92',
  'LDLC ASVEL': 'LDLC ASVEL',
  Monaco: 'AS Monaco Basket',
  Dijon: 'JDA Dijon',
  'Le Mans': 'Le Mans Sarthe Basket',
  'Pau-Orthez': 'Élan Béarnais Pau-Lacq-Orthez',
  Strasbourg: 'SIG Strasbourg',
  Limoges: 'Limoges CSP',
  Nanterre: 'Nanterre 92',
  Gravelines: 'BCM Gravelines-Dunkerque',
  'JL-Bourg': 'JL Bourg',
  Roanne: 'Chorale Roanne Basket',
  Cholet: 'Cholet Basket',
  Orleans: 'Orléans Loiret Basket',
  'Le Portel': 'ESSM Le Portel',
  'Paris Basket': 'Paris Basketball',
  Chalons: 'Champagne Basket',
  'Fos Provence': 'Fos Provence',
}
