// TODO: refact all constants

export const teams = {
  'paris-levallois': 'Metropolitans 92',
  villeurbanne: 'LDLC ASVEL',
  monaco: 'AS Monaco Basket',
  dijon: 'JDA Dijon',
  'le-mans': 'Le Mans Sarthe Basket',
  'pau-orthez': 'Élan Béarnais Pau-Lacq-Orthez',
  strasbourg: 'SIG Strasbourg',
  limoges: 'Limoges CSP',
  nanterre: 'Nanterre 92',
  gravelines: 'BCM Gravelines-Dunkerque',
  bourg: 'JL Bourg',
  roanne: 'Chorale Roanne Basket',
  cholet: 'Cholet Basket',
  orleans: 'Orléans Loiret Basket',
  'le-portel': 'ESSM Le Portel',
  'paris-basket': 'Paris Basketball',
  'chalons-en-champagne': 'Champagne Basket',
  'fos-provence': 'Fos Provence',
}

export const computeTeams = {
  Metropolitans: 'Metropolitans 92',
  'LDLC ASVEL': 'LDLC ASVEL',
  Monaco: 'AS Monaco Basket',
  Dijon: 'JDA Dijon',
  'Le Mans': 'Le Mans Sarthe Basket',
  'Pau-Orthez': 'Élan Béarnais Pau-Lacq-Orthez',
  Strasbourg: 'SIG Strasbourg',
  Limoges: 'Limoges CSP',
  Nanterre: 'Nanterre 92',
  Gravelines: 'BCM Gravelines-Dunkerque',
  'JL-Bourg': 'JL Bourg',
  Roanne: 'Chorale Roanne Basket',
  Cholet: 'Cholet Basket',
  Orleans: 'Orléans Loiret Basket',
  'Le Portel': 'ESSM Le Portel',
  'Paris Basket': 'Paris Basketball',
  Chalons: 'Champagne Basket',
  'Fos Provence': 'Fos Provence',
}

export const teamIds = {
  14: 'Metropolitans 92',
  26: 'LDLC ASVEL',
  16: 'AS Monaco Basket',
  10: 'JDA Dijon',
  23: 'Le Mans Sarthe Basket',
  3007: 'Élan Béarnais Pau-Lacq-Orthez',
  25: 'SIG Strasbourg',
  27: 'Limoges CSP',
  21: 'Nanterre 92',
  17: 'BCM Gravelines-Dunkerque',
  24: 'JL Bourg',
  19: 'Chorale Roanne Basket',
  18: 'Cholet Basket',
  15: 'Orléans Loiret Basket',
  11: 'ESSM Le Portel',
  108: 'Paris Basketball',
  12: 'Champagne Basket',
  110: 'Fos Provence',
}

export const teamRapidApi = {
  'paris-levallois': 'Levallois',
  villeurbanne: 'Lyon-Villeurbanne',
  monaco: 'Monaco',
  dijon: 'Dijon',
  'le-mans': 'Le Mans',
  'pau-orthez': 'Pau-Orthez',
  strasbourg: 'Strasbourg',
  limoges: 'Limoges',
  nanterre: 'Nanterre',
  gravelines: 'Gravelines-Dunkerque',
  bourg: 'JL Bourg',
  roanne: 'Roanne',
  cholet: 'Cholet',
  orleans: 'Orleans',
  'le-portel': 'Le Portel',
  'paris-basket': 'Paris',
  'chalons-en-champagne': 'Chalons-Reims',
  'fos-provence': 'Fos-sur-Mer',
}
